---
# Got errors:
#   error: "net.bridge.bridge-nf-call-ip6tables" is an unknown key
#   error: "net.bridge.bridge-nf-call-iptables" is an unknown key
#   error: "net.bridge.bridge-nf-call-arptables" is an unknown key
# That's why ignoreerrors is turned on

- name: all.disable_ipv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6"
          state=present
          value=1
          ignoreerrors=yes

- name: default.disable_ipv6
  sysctl: name="net.ipv6.conf.default.disable_ipv6"
          state=present
          value=1
          ignoreerrors=yes
